name: Integration Tests

on:
  push: {}

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        secret-store:
          - none
          - libsecret
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Setup Python
        uses: chrisgavin/setup-python-action@41e811a2a0fcb80d8226f553c3e47ab7c2d5465c
      - name: Setup (Linux)
        run: |
          sudo cp ./integration_tests/apt-key.asc /etc/apt/trusted.gpg.d/
          sudo cp ./integration_tests/apt-source.list /etc/apt/sources.list.d/
          sudo apt-get update
          sudo apt-get install --yes slack-desktop xvfb dbus-x11 gnome-keyring libgirepository1.0-dev
      - name: Cache Playwright Browsers
        uses: actions/cache@48af2dc4a9e8278b89d7fa154b955c30c6aaab09
        with:
          path: ~/.cache/ms-playwright/
          key: playwright
      - name: Setup
        run: |
          task setup
          poetry run playwright install
      - name: Run Test
        env:
          SLACKTOKEN_INTEGRATION_TEST_WORKSPACE: ${{ secrets.INTEGRATION_TEST_WORKSPACE }}
          SLACKTOKEN_INTEGRATION_TEST_USER: ${{ secrets.INTEGRATION_TEST_USER }}
          SLACKTOKEN_INTEGRATION_TEST_PASSWORD: ${{ secrets.INTEGRATION_TEST_PASSWORD }}
        run: ./integration_tests/linux-${{ matrix.secret-store }}/run.sh
