name: Integration Tests

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  check-permissions:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.id == github.event.pull_request.base.repo.id }}
    runs-on: ubuntu-20.04
    steps:
      - name: Check Permissions
        run: "true"

  linux:
    needs: check-permissions
    strategy:
      fail-fast: false
      matrix:
        secret-store:
          - none
          - libsecret
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Setup Python
        uses: chrisgavin/setup-python-action@994a4a6e3763472259ab60c1d214ecff7e7feb15
      - name: Setup (Linux)
        run: |
          sudo cp ./integration_tests/apt-key.asc /etc/apt/trusted.gpg.d/
          sudo cp ./integration_tests/apt-source.list /etc/apt/sources.list.d/
          sudo apt-get update
          sudo apt-get install --yes slack-desktop xvfb dbus-x11 gnome-keyring libgirepository1.0-dev
      - name: Cache Playwright Browsers
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
        with:
          path: ~/.cache/ms-playwright/
          key: playwright-linux
      - name: Setup
        run: |
          task setup
          poetry run playwright install
      - name: Run Test
        env:
          SLACKTOKEN_INTEGRATION_TEST_WORKSPACE: ${{ secrets.INTEGRATION_TEST_WORKSPACE }}
          SLACKTOKEN_INTEGRATION_TEST_USER: ${{ secrets.INTEGRATION_TEST_USER }}
          SLACKTOKEN_INTEGRATION_TEST_PASSWORD: ${{ secrets.INTEGRATION_TEST_PASSWORD }}
          SLACKTOKEN_INTEGRATION_TEST_TOTP_SEED: ${{ secrets.INTEGRATION_TEST_TOTP_SEED }}
        run: ./integration_tests/linux-${{ matrix.secret-store }}/run.sh

  macos:
    needs: check-permissions
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Setup Python
        uses: chrisgavin/setup-python-action@994a4a6e3763472259ab60c1d214ecff7e7feb15
      - name: Setup (macOS)
        run: |
          cp ./integration_tests/macos/build.keychain-db ~/Library/Keychains/
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings build.keychain

          brew install --cask slack
      - name: Cache Playwright Browsers
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
        with:
          path: ~/Library/Caches/ms-playwright/
          key: playwright-macos
      - name: Setup
        env:
          SYSTEM_VERSION_COMPAT: "0" # Workaround for python-poetry/poetry#7161.
        run: |
          task setup
          poetry run playwright install
      - name: Run Test
        env:
          SLACKTOKEN_INTEGRATION_TEST_WORKSPACE: ${{ secrets.INTEGRATION_TEST_WORKSPACE }}
          SLACKTOKEN_INTEGRATION_TEST_USER: ${{ secrets.INTEGRATION_TEST_USER }}
          SLACKTOKEN_INTEGRATION_TEST_PASSWORD: ${{ secrets.INTEGRATION_TEST_PASSWORD }}
          SLACKTOKEN_INTEGRATION_TEST_TOTP_SEED: ${{ secrets.INTEGRATION_TEST_TOTP_SEED }}
        run: ./integration_tests/macos/run.sh

  windows:
    needs: check-permissions
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Setup Python
        uses: chrisgavin/setup-python-action@994a4a6e3763472259ab60c1d214ecff7e7feb15
      - name: Setup (Windows)
        run: choco install slack
      - name: Cache Playwright Browsers
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
        with:
          path: ~/AppData/Local/ms-playwright/
          key: playwright-windows
      - name: Setup
        run: |
          task setup
          poetry run playwright install
      - name: Run Test
        env:
          SLACKTOKEN_INTEGRATION_TEST_WORKSPACE: ${{ secrets.INTEGRATION_TEST_WORKSPACE }}
          SLACKTOKEN_INTEGRATION_TEST_USER: ${{ secrets.INTEGRATION_TEST_USER }}
          SLACKTOKEN_INTEGRATION_TEST_PASSWORD: ${{ secrets.INTEGRATION_TEST_PASSWORD }}
          SLACKTOKEN_INTEGRATION_TEST_TOTP_SEED: ${{ secrets.INTEGRATION_TEST_TOTP_SEED }}
        run: ./integration_tests/windows/run.ps1
