name: Report Errors

on:
  workflow_run:
    workflows: [Integration Tests]
    types:
      - completed
    branches:
      - master

permissions:
  actions: write
  issues: write

jobs:
  report-errors:
    name: Report Errors
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.event == 'schedule' }}
    steps:
      - name: Re-run Workflow
        if: ${{ github.event.workflow_run.conclusion != 'success' && github.event.workflow_run.run_attempt < 5 }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}
        with:
          script: |
            console.log("Retrying run.");
            github.request("POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun-failed-jobs", {
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: process.env.RUN_ID,
            });

      - name: Create or Update Issue
        uses: chrisgavin/create-or-update-issue-action@6c33f901f0e5b25f96409e670b49814902d35fa3
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.run_attempt >= 5 }}
        with:
          title: Integration tests are currently failing.
          body: |-
            See ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }} for more details about the failure.
          assignees: chrisgavin
          close: ${{ github.event.workflow_run.conclusion == 'success' }}
