name: Report Errors

on:
  workflow_run:
    workflows: [Integration Tests]
    types:
      - completed
    branches:
      - master

permissions:
  issues: write

jobs:
  report-errors:
    name: Report Errors
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.event == 'schedule' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit
      - name: Create or Update Issue
        uses: chrisgavin/create-or-update-issue-action@3e480bdd473102c786d422df827fd491704a3244 # 0.0.5
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.run_attempt >= 5 }}
        with:
          title: Integration tests are currently failing.
          body: |-
            See ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }} for more details about the failure.
          assignees: chrisgavin
          close: ${{ github.event.workflow_run.conclusion == 'success' }}
