on:
  workflow_run:
    workflows: [Integration Tests]
    types:
      - completed

permissions:
  actions: write

jobs:
  retry:
    runs-on: ubuntu-24.04
    steps:
      - name: Re-run Workflow
        if: ${{ github.event.workflow_run.conclusion != 'success' && github.event.workflow_run.run_attempt < 5 }}
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}
        with:
          script: |
            console.log("Retrying run.");
            github.request("POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun-failed-jobs", {
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: process.env.RUN_ID,
            });
